/*  _____ _______         _                      _
 * |_   _|__   __|       | |                    | |
 *   | |    | |_ __   ___| |___      _____  _ __| | __  ___ ____
 *   | |    | | '_ \ / _ \ __\ \ /\ / / _ \| '__| |/ / / __|_  /
 *  _| |_   | | | | |  __/ |_ \ V  V / (_) | |  |   < | (__ / /
 * |_____|  |_|_| |_|\___|\__| \_/\_/ \___/|_|  |_|\_(_)___/___|
 *                                _
 *              ___ ___ ___ _____|_|_ _ _____
 *             | . |  _| -_|     | | | |     |  LICENCE
 *             |  _|_| |___|_|_|_|_|___|_|_|_|
 *             |_|
 *
 *   PROGRAMOVÁNÍ  <>  DESIGN  <>  PRÁCE/PODNIKÁNÍ  <>  HW A SW
 *
 * Tento zdrojový kód je součástí výukových seriálů na
 * IT sociální síti WWW.ITNETWORK.CZ
 *
 * Kód spadá pod licenci prémiového obsahu a vznikl díky podpoře
 * našich členů. Je určen pouze pro osobní užití a nesmí být šířen.
 * Více informací na http://www.itnetwork.cz/licence
 */
package cz.itnetwork.entity.repository;

import cz.itnetwork.entity.PersonEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface PersonRepository extends JpaRepository<PersonEntity, Long> {

    /**
     * Retrieves a list of PersonEntity objects based on the given 'hidden' status.
     *
     * @param hidden A boolean indicating whether the person is hidden or not.
     * @return A list of PersonEntity objects matching the provided 'hidden' status.
     */
    List<PersonEntity> findByHidden(boolean hidden);

    /**
     * Retrieves the total revenue generated by invoices associated with a specific seller.
     *
     * @param sellerId The ID of the seller whose revenue is to be calculated.
     * @return The total revenue generated by invoices associated with the specified seller.
     */
    @Query(value = "SELECT SUM(price) AS revenue FROM invoice WHERE seller_id = :sellerId", nativeQuery = true)
    Long getRevenue(@Param("sellerId") Long sellerId);

}
